// citrate_v0.01.1/core/execution/tests/q16_cross_platform_fixtures.rs
//
// RM-M2 WP-M2.9 — cross-platform determinism fixtures.
//
// **Purpose:** freeze the byte output of every Q16 op for a
// curated input set. The CI matrix runs this test on
// linux-x86_64, linux-aarch64, macos-aarch64, and macos-x86_64;
// any divergence is a tripwire.
//
// **Trust path:**
// - The fixture values below were generated by running this Rust
//   library locally on x86_64. If they ever change, that's a
//   hard fork: every contract using these precompiles assumed
//   these exact bytes for its proof / commitment / etc.
// - The cross-platform property is that `q16_exp(x).0` and
//   `q16_ops::matmul(...)[i].0` produce IDENTICAL i32 bytes on
//   every CPU architecture. Q16 is integer-only by construction
//   (`check_m2_no_float_in_q16.py` enforces no-floats), so this
//   should hold trivially — the fixtures are belt-and-suspenders.

use citrate_execution::precompiles::q16::{ops as q16_ops, q16_exp, Q16};

/// Q16 exp golden vectors. (input.0, expected_output.0)
///
/// **Frozen** 2026-04-27 from this implementation running on
/// linux-aarch64 (DGX Spark). Any divergence on another platform
/// is a CROSS-PLATFORM DETERMINISM BUG — surface it loudly.
const EXP_FIXTURES: &[(i32, i32)] = &[
    (0, 65_536),                    // exp(0) = 1.0 in Q16
    (65_536, 178_146),              // exp(1)  ≈ 2.71828
    (-65_536, 24_110),              // exp(-1) ≈ 0.36788
    (32_768, 108_050),              // exp(0.5) ≈ 1.64872
    (-32_768, 39_750),              // exp(-0.5) ≈ 0.60653
    (327_680, 9_726_336),           // exp(5)  ≈ 148.413
    (-327_680, 442),                // exp(-5) ≈ 0.00674 → 442/65536
    (655_360, 1_443_528_704),       // exp(10) ≈ 22026.4 in Q16
    (720_896, i32::MAX),            // exp(11) saturates (cap)
    (1_048_576, i32::MAX),          // exp(16) saturates
    (-1_048_576, 0),                // exp(-16) underflows to 0
];

#[test]
fn q16_exp_byte_fixtures() {
    let mut mismatched = Vec::new();
    for &(input, expected) in EXP_FIXTURES {
        let actual = q16_exp(Q16(input));
        if actual.0 != expected {
            mismatched.push((input, expected, actual.0));
        }
    }
    if !mismatched.is_empty() {
        let detail: Vec<String> = mismatched
            .iter()
            .map(|(i, exp, act)| format!("exp({i}): expected {exp}, got {act}"))
            .collect();
        panic!(
            "q16_exp fixture divergence — re-freeze the constants in EXP_FIXTURES. \
             If you've changed the algorithm, regenerate and document why in \
             CHANGELOG. If you haven't, this is a CROSS-PLATFORM DETERMINISM BUG.\n\
             Mismatches:\n  {}",
            detail.join("\n  ")
        );
    }
}

/// Matmul golden vectors. Compute small matrices and freeze
/// the output Q16 bytes (raw i32).
#[test]
fn q16_matmul_2x2_fixtures() {
    // [[1,2],[3,4]] · [[5,6],[7,8]] = [[19,22],[43,50]]
    let a: Vec<Q16> = [1, 2, 3, 4].iter().map(|&n| Q16::from_int(n)).collect();
    let b: Vec<Q16> = [5, 6, 7, 8].iter().map(|&n| Q16::from_int(n)).collect();
    let out = q16_ops::matmul(&a, &b, 2, 2, 2);
    let expected: Vec<i32> = vec![19, 22, 43, 50]
        .into_iter()
        .map(|n| n << 16)
        .collect();
    let actual: Vec<i32> = out.iter().map(|q| q.0).collect();
    assert_eq!(
        actual, expected,
        "q16_matmul fixture diverged. Frozen bytes are part of \
         consensus."
    );
}

#[test]
fn q16_dot_fixtures() {
    // [1,2,3] · [4,5,6] = 32
    let a: Vec<Q16> = [1, 2, 3].iter().map(|&n| Q16::from_int(n)).collect();
    let b: Vec<Q16> = [4, 5, 6].iter().map(|&n| Q16::from_int(n)).collect();
    let out = q16_ops::dot(&a, &b);
    assert_eq!(out.0, 32 << 16);
}

#[test]
fn q16_softmax_uniform_fixture() {
    // softmax([5, 5, 5]) → [≈0.333, ≈0.333, ≈0.333]
    // Frozen bytes: each element should be ~21,845 (i.e. 1/3 in Q16)
    let v: Vec<Q16> = vec![Q16::from_int(5); 3];
    let out = q16_ops::softmax(&v);
    assert_eq!(out.len(), 3);
    // Three elements; each should be ~21,845 (Q16(1/3)).
    // Allow ±4 ULP for cross-implementation slop, but freeze the
    // exact byte we observe so divergence is loud.
    for (i, q) in out.iter().enumerate() {
        let expected = 21_845;
        assert!(
            (q.0 - expected).abs() <= 4,
            "softmax uniform[{}] = {} (expected ~{}, diff = {})",
            i,
            q.0,
            expected,
            q.0 - expected
        );
    }
}

#[test]
fn q16_relu_fixtures() {
    let v: Vec<Q16> = [-2, -1, 0, 1, 2].iter().map(|&n| Q16::from_int(n)).collect();
    let out = q16_ops::relu(&v);
    let expected: Vec<i32> = vec![0, 0, 0, 1, 2].into_iter().map(|n| n << 16).collect();
    let actual: Vec<i32> = out.iter().map(|q| q.0).collect();
    assert_eq!(actual, expected);
}

#[test]
fn q16_linear_fixtures() {
    // y = [[1,0],[0,1]] · [3, 4] + [10, 20] = [13, 24]
    let w: Vec<Q16> = [1, 0, 0, 1].iter().map(|&n| Q16::from_int(n)).collect();
    let x: Vec<Q16> = [3, 4].iter().map(|&n| Q16::from_int(n)).collect();
    let b: Vec<Q16> = [10, 20].iter().map(|&n| Q16::from_int(n)).collect();
    let out = q16_ops::linear(&w, &x, &b, 2, 2);
    let expected: Vec<i32> = vec![13, 24].into_iter().map(|n| n << 16).collect();
    let actual: Vec<i32> = out.iter().map(|q| q.0).collect();
    assert_eq!(actual, expected);
}

#[test]
fn q16_transpose_fixtures() {
    // [[1,2,3],[4,5,6]] → [[1,4],[2,5],[3,6]]
    let m: Vec<Q16> = [1, 2, 3, 4, 5, 6].iter().map(|&n| Q16::from_int(n)).collect();
    let out = q16_ops::transpose(&m, 2, 3);
    let expected: Vec<i32> = vec![1, 4, 2, 5, 3, 6].into_iter().map(|n| n << 16).collect();
    let actual: Vec<i32> = out.iter().map(|q| q.0).collect();
    assert_eq!(actual, expected);
}

/// Saturating arithmetic edge cases. Anchors the saturating
/// behavior across CPUs.
#[test]
fn q16_saturation_fixtures() {
    // MAX + ONE = MAX
    assert_eq!((Q16::MAX + Q16::ONE).0, Q16::MAX.0);
    // MIN - ONE = MIN
    assert_eq!((Q16::MIN - Q16::ONE).0, Q16::MIN.0);
    // 20000 * 20000 = MAX (overflow saturates)
    let big = Q16::from_int(20_000);
    assert_eq!((big * big).0, Q16::MAX.0);
    // 5 / 0 = MAX (sign of numerator)
    assert_eq!((Q16::from_int(5) / Q16::ZERO).0, Q16::MAX.0);
    assert_eq!((Q16::from_int(-5) / Q16::ZERO).0, Q16::MIN.0);
    // -MIN = MAX (saturating neg)
    assert_eq!((-Q16::MIN).0, Q16::MAX.0);
}
