#!/usr/bin/env python3
"""panic_ledger.py <sites.json> <out.md> — generate the PANIC-S1 site ledger.

One row per production panic site from panic-inventory.sh --sites, grouped by
tier and file. Tiers are PROVISIONAL (path-based, from the PANIC-S1 sprint §1)
and are confirmed or overridden during triage. The Disposition / PR columns are
filled in as work lands; a site is closed when its row has both. Regenerate to
refresh the open set: rows for sites that no longer exist simply disappear, and
the ratchet guarantees none reappear.
"""
import collections
import datetime
import json
import re
import sys

T1_CRATES = {"core/execution", "core/economics", "core/consensus", "core/storage",
             "core/primitives", "core/bridge", "crates/citrate-commd", "crates/citrate-commd-fold"}
T2_CRATES = {"core/network", "core/api", "core/sequencer", "core/mcp", "core/marketplace", "core/signing"}
NODE_T1 = re.compile(r"node/src/(canonical_apply|producer|block_|import|registry_sync|sync|state_)")
NODE_T2 = re.compile(r"node/src/(rpc|p2p|network|mempool|gossip)")


def tier(s):
    c, f = s["crate"], s["file"]
    if c == "node":
        if "/bin/" in f:
            return "T3"
        return "T1" if NODE_T1.search(f) else ("T2" if NODE_T2.search(f) else "T3")
    if c in T1_CRATES:
        return "T1"
    if c in T2_CRATES:
        return "T2"
    return "T3"


def main():
    sites = json.load(open(sys.argv[1]))
    by = collections.defaultdict(lambda: collections.defaultdict(list))
    for s in sites:
        by[tier(s)][s["file"]].append(s)
    counts = {t: sum(len(v) for v in by[t].values()) for t in ("T1", "T2", "T3")}
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    out = [
        "---", f"created: {now}", "branch: reroll/panic-s1",
        "author: generated by scripts/ci/panic_ledger.py (PANIC-S1 WP-0)", "status: active", "---", "",
        "# PANIC-S1 production panic-site ledger", "",
        "Generated from `scripts/ci/panic-inventory.sh --sites`; regenerate with",
        "`scripts/ci/panic-inventory.sh --sites /tmp/s.json && scripts/ci/panic_ledger.py /tmp/s.json docs/panic-s1/LEDGER.md`.",
        "Tiers are **provisional** (path-based); confirm per site during triage.",
        "Dispositions: CONVERT · CHECKED · SAFE-INDEX · PROVE+KEEP (see sprint §2).", "",
        f"**Open sites: {len(sites)}** — T1 {counts['T1']} · T2 {counts['T2']} · T3 {counts['T3']}", "",
    ]
    for t, title in (("T1", "T1: consensus-deterministic"), ("T2", "T2: untrusted input, non-consensus"),
                     ("T3", "T3: node-local / ops")):
        out += [f"## {title} ({counts[t]})", ""]
        for f in sorted(by[t]):
            rows = by[t][f]
            lints = collections.Counter(r["lint"] for r in rows)
            out += [f"### `{f}` ({len(rows)}: " + ", ".join(f"{k} {v}" for k, v in lints.most_common()) + ")", "",
                    "| line:col | lint | disposition | PR |", "|---|---|---|---|"]
            out += [f"| {r['line']}:{r['col']} | {r['lint']} |  |  |" for r in rows]
            out.append("")
    open(sys.argv[2], "w").write("\n".join(out))
    print(f"ledger: {len(sites)} sites (T1 {counts['T1']}, T2 {counts['T2']}, T3 {counts['T3']}) -> {sys.argv[2]}")


if __name__ == "__main__":
    main()
