#!/usr/bin/env python3
"""Sync the federation contract artifact into the CLI's vendored copy.

Source of truth:
    citrate-federation/contract/federation-contract.json
generated by:
    citrate-federation/scripts/gen-contract.mjs

    python3 scripts/sync-federation-contract.py          # overwrite the vendored copy
    python3 scripts/sync-federation-contract.py --check   # gate: non-zero if it drifted

WHY THIS EXISTS
    `cli/federation-contract.json` is compiled into the binary by `include_str!`
    in `cli/src/commands/devx.rs`, so whatever was vendored at build time is what
    ships. There is no runtime fetch and no way to notice it is old.

    It went stale exactly that way: committed 2026-07-26, the day BEFORE the
    2026-07-27 redeployment, and left nine contracts behind (AnchorRegistry,
    MeetingRegistry, GovernanceTemplateRegistry, GovernanceProtocolFactory,
    PolicyBinding, CapabilityGrant, VoteAllowance, Sortition, ValidatorRegistry)
    with provenance still reading 2026-07-23.

    THE IMPACT WAS LATENT, NOT REALISED — measured, not assumed. `devx contract`
    surfaces only chain / aaStack / membership / identity / entitlements /
    gateway, and every one of those was byte-identical between the stale and
    current artifacts. The drift lived entirely in `contracts` and `provenance`,
    which the command has no section for. `predict-address` reads
    aaStack.CitrateWalletFactory and aaStack.CitrateWallet, also unchanged.

    So nobody was served a wrong address. What existed was a vendored artifact
    drifting with nothing watching it, in a repo where the equivalent copies in
    both SDKs have had a sync script and a drift gate since DEVX-S0. This one had
    neither, which is why it was the copy that rotted and the last one anybody
    checked. The moment `devx` grows a `contracts` section — or anything else
    reads those keys — the staleness stops being latent, silently.

    Deliberately byte-verbatim, like the SDK copies, so the comparison is exact
    and cross-language rather than a semantic diff that has to be trusted.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LABS_ROOT = REPO_ROOT.parent
FEDERATION = LABS_ROOT / "citrate-federation"
CANONICAL = FEDERATION / "contract" / "federation-contract.json"
VENDORED = REPO_ROOT / "cli" / "federation-contract.json"


def federation_branch() -> str:
    try:
        r = subprocess.run(
            ["git", "-C", str(FEDERATION), "branch", "--show-current"],
            capture_output=True, text=True, timeout=10,
        )
        return r.stdout.strip() or "(detached)"
    except Exception:
        return "(unknown)"


def warn_if_not_main() -> None:
    """CI compares against citrate-federation@main; a local run compares against
    whatever is checked out there. Say which, or the result is unreadable.

    This is not hypothetical. The first run of this very script reported "in
    sync" against a sibling sitting on an old feature branch that happened to
    match the stale vendored copy — agreeing with the bug it exists to catch.
    """
    branch = federation_branch()
    if branch not in ("main", "master"):
        print(
            f"[sync-federation-contract] WARNING: citrate-federation is on '{branch}', not main.\n"
            f"  CI compares against main (see the `ref: main` checkout in the SDK drift jobs).\n"
            f"  This run reflects '{branch}'. To compare against main:\n"
            f"    git -C ../citrate-federation show main:contract/federation-contract.json",
            file=sys.stderr,
        )


def canonical_at_ref(ref: str) -> str:
    """Read the canonical artifact from a git ref instead of the working tree.

    `--ref main` reproduces what CI compares against no matter which branch the
    sibling has checked out, which is the only way to get a trustworthy answer
    on a machine where 20+ federation repos sit on feature branches.
    """
    r = subprocess.run(
        ["git", "-C", str(FEDERATION), "show", f"{ref}:contract/federation-contract.json"],
        capture_output=True, text=True, timeout=30,
    )
    if r.returncode != 0:
        raise RuntimeError(f"cannot read contract at ref '{ref}': {r.stderr.strip()}")
    return r.stdout


def main() -> int:
    argv = sys.argv[1:]
    check = "--check" in argv
    ref = None
    if "--ref" in argv:
        i = argv.index("--ref")
        if i + 1 >= len(argv):
            print("[sync-federation-contract] --ref needs a value, e.g. --ref main", file=sys.stderr)
            return 2
        ref = argv[i + 1]

    if ref:
        try:
            raw = canonical_at_ref(ref)
        except RuntimeError as exc:
            print(f"[sync-federation-contract] {exc}", file=sys.stderr)
            return 1
        print(f"[sync-federation-contract] reading canonical from citrate-federation@{ref}", flush=True)
    else:
        warn_if_not_main()
        if not CANONICAL.exists():
            print(
                f"[sync-federation-contract] canonical not found at {CANONICAL}\n"
                "  Ensure citrate-federation is a sibling under citrate-labs/ and run\n"
                "  `node scripts/gen-contract.mjs` there first.",
                file=sys.stderr,
            )
            return 1
        raw = CANONICAL.read_text(encoding="utf-8")

    # Minimal shape gate so a malformed canonical cannot be baked into a binary.
    doc = json.loads(raw)
    if doc.get("schemaVersion") != 1:
        print(f"[sync-federation-contract] unexpected schemaVersion {doc.get('schemaVersion')}",
              file=sys.stderr)
        return 1
    if doc.get("chain", {}).get("chainId") != 40204:
        print(f"[sync-federation-contract] chainId {doc.get('chain', {}).get('chainId')}, "
              f"expected 40204", file=sys.stderr)
        return 1

    if check:
        if not VENDORED.exists():
            print(f"[sync-federation-contract] no vendored copy at {VENDORED}", file=sys.stderr)
            return 1
        if VENDORED.read_text(encoding="utf-8") != raw:
            print(
                "[sync-federation-contract] cli/federation-contract.json is OUT OF SYNC.\n"
                "  Run `python3 scripts/sync-federation-contract.py` and commit.\n"
                "  NOTE: this file is include_str!'d into the CLI, so a stale copy ships\n"
                "  silently — the binary compiles and prints the wrong contract table.",
                file=sys.stderr,
            )
            return 1
        print("[sync-federation-contract] vendored contract matches canonical ✓")
        return 0

    VENDORED.parent.mkdir(parents=True, exist_ok=True)
    VENDORED.write_text(raw, encoding="utf-8")
    print(
        f"[sync-federation-contract] wrote {VENDORED.relative_to(REPO_ROOT)} "
        f"({len(doc['contracts'])} contracts, deployedAt {doc['provenance']['deployedAt']})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
